//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreecoLuckyDraw.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    public partial class CAMPAIGN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAMPAIGN()
        {
            LOGO = "/Assets/img/preeco.png";
            BACKGROUND = "/Assets/img/nentron.png";
            this.CAMPAIGN_DETAIL = new HashSet<CAMPAIGN_DETAIL>();
            this.JOINERs = new HashSet<JOINER>();
        }

        public int IDCAMPAIGN { get; set; }
        public string NAME { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> EXPIREDDATE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<int> WINNERS { get; set; }
        public string LOGO { get; set; }
        public string BACKGROUND { get; set; }
        public string COLORTEXT { get; set; }
        public string COLORBG { get; set; }
        public string COLORBTN_BG { get; set; }
        public string COLORBTN_TEXT { get; set; }
        public Nullable<int> ID { get; set; }

        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPAIGN_DETAIL> CAMPAIGN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOINER> JOINERs { get; set; }
        [NotMapped]
        public List<CAMPAIGN> listCampaign { get; internal set; }
        [NotMapped]
        public HttpPostedFileBase UploadLogo { get; set; }
        public HttpPostedFileBase UploadBackground { get; set; }
    }
}
