//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreecoLuckyDraw.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class CAMPAIGN_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAMPAIGN_DETAIL()
        {
            this.WINNERs = new HashSet<WINNER>();
        }

        public int IDDETAIL { get; set; }
        public int IDCAMPAIGN { get; set; }
        public int IDPRIZE { get; set; }
        public int IDGIFT { get; set; }
        public Nullable<int> USAGELIMIT { get; set; }
        public Nullable<System.DateTime> WINDATE { get; set; }

        public virtual CAMPAIGN CAMPAIGN { get; set; }
        public virtual GIFT GIFT { get; set; }
        public virtual PRIZE PRIZE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WINNER> WINNERs { get; set; }
        [NotMapped]
        public List<CAMPAIGN_DETAIL> listCampDetail { get; internal set; }
    }
}
