//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreecoLuckyDraw.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class GIFT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIFT()
        {
            IMAGE = "/Assets/img/preeco.png";

            this.CAMPAIGN_DETAIL = new HashSet<CAMPAIGN_DETAIL>();
        }

        public int IDGIFT { get; set; }
        public string NAME { get; set; }
        public string IMAGE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<int> ID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPAIGN_DETAIL> CAMPAIGN_DETAIL { get; set; }
        public virtual USER USER { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }

        [NotMapped]
        public List<GIFT> listGift { get; internal set; }
    }
}
