//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreecoLuckyDraw.Models
{
    using System;
    using System.Collections.Generic;

    public partial class JOINER
    {
        public int ID { get; set; }
        public string IDJOINER { get; set; }
        public string PHONE { get; set; }
        public string NAME { get; set; }
        public string DATEOFBIRTH { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> IDCAMPAIGN { get; set; }

        public virtual CAMPAIGN CAMPAIGN { get; set; }
    }
}
