//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreecoLuckyDraw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUCKYNUMBER
    {
        public int ID { get; set; }
        public Nullable<int> NUMB { get; set; }
        public string CONTENTS { get; set; }
        public string IMAGE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string NOTE { get; set; }
    }
}
