//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------ 

namespace PreecoLuckyDraw.Models
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;

    using System.Collections.Generic;

    public partial class PRIZE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRIZE()
        {
            this.CAMPAIGN_DETAIL = new HashSet<CAMPAIGN_DETAIL>();
        }

        public int IDPRIZE { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPAIGN_DETAIL> CAMPAIGN_DETAIL { get; set; }
        [NotMapped]
        public List<PRIZE> listPrize { get; internal set; }
    }
}
