//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreecoLuckyDraw.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CAMPAIGNs = new HashSet<CAMPAIGN>();
            this.GIFTs = new HashSet<GIFT>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string NAME { get; set; }
        public string DATEOFBIRTH { get; set; }
        [Required(ErrorMessage = "Phone is required")]
        [StringLength(10, ErrorMessage = "type your Phone")]
        [RegularExpression(@"^.{10,}$", ErrorMessage = "type your Phone")]
        public string PHONE { get; set; }
        [Required(ErrorMessage = "Password is required")]
        public string PASSWORD { get; set; }
        public Nullable<int> STATUSS { get; set; }
        //[DataType(DataType.Password)]
        //[Display(Name = "Confirm Password")]
        //[Compare("Password", ErrorMessage = "Password and confirm password must be same!")]
        //public string ConfirmPassword { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPAIGN> CAMPAIGNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIFT> GIFTs { get; set; }
    }
}
